### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

\### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int32
b: <class 'torch.Tensor'>, torch.int32
c: <class 'torch.Tensor'>, torch.int32
d: <class 'numpy.ndarray'>, int32


### Function 1 - *torch.arange()*

In [5]:
# Example 1 - 提供類似於 range 的功能
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Example 2 - 可以同時設定 start, end, step
torch.arange(0,20,5)

tensor([ 0,  5, 10, 15])

### Function 2 - tensor.full()

In [29]:
# Example 1 - 可以產生多維度的特定數值
torch.full((5,3), 2)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

In [35]:
# Example 2 - 可以產生 0 維 及 1 維的資料
print(torch.full((), 10))
print(torch.full((1,), 10))

tensor(10)
tensor([10])


### Function 3 - torch.cat()

In [37]:
# Example 1 - 可以將兩個 tensor 合併
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8,9],[10,11,12]])
torch.cat([x,y])

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [38]:
# Example 2 - 也可以依照不同緯度進行合併
torch.cat([x,y], dim=1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

### Function 4 - torch.movedim()

In [39]:
# Example 1 - 可以轉換 tensor 的 dim
x = torch.tensor([[[1],[2]], [[3],[4]], [[5],[6]]])

In [40]:
x.shape

torch.Size([3, 2, 1])

In [42]:
y = torch.movedim(x, 2, 1)
y

tensor([[[1, 2]],

        [[3, 4]],

        [[5, 6]]])

In [43]:
y.shape

torch.Size([3, 1, 2])

In [46]:
# Example 2 - 任何緯度的調整都可以, 順序依照原序列排序
z = torch.movedim(x, 1, 0)
z

tensor([[[1],
         [3],
         [5]],

        [[2],
         [4],
         [6]]])

In [47]:
z.shape

torch.Size([2, 3, 1])